name: Build
on: [push]

env:
  CONTAINER_MANAGER: podman
  AWS_ACCOUNT_ID: 700707183175
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: eu-central-1
  REPOSITORY_NAME: flagbit/technology-radar
  KUBECONFIG_FILE: ${{ secrets.KUBECONFIG }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # - run: make build
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{env.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{env.AWS_SECRET_ACCESS_KEY}}
          aws-region: ${{env.AWS_DEFAULT_REGION}}
      - run: aws --region eu-central-1 eks update-kubeconfig --name eks-production
      - run: kubectl -n technology-radar get pods