name: Build
on: [push]
env:
    CONTAINER_MANAGER: podman
    AWS_ACCOUNT_ID: 700707183175
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    REPOSITORY_NAME: flagbit-technology-radar
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: make build
  publish:
    needs: build
    name: Push Image
    runs-on: ubuntu-latest
    steps:
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{env.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{env.AWS_SECRET_ACCESS_KEY}}
          aws-region: eu-central-1
      - uses: aws-actions/amazon-ecr-login@v1
      - run: make publish